# Generated by Django 4.0.2 on 2022-02-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='missed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
