# Generated by Django 4.0.2 on 2022-02-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_appointment_finished_appointment_missed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
