# Generated by Django 4.0.2 on 2022-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Rescheduled', 'Rescheduled'), ('Passed', 'Passed')], default='New', max_length=200, null=True),
        ),
    ]
