# Generated by Django 4.0.2 on 2022-02-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_appointment_date_created_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rescheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
